[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jax-morph"
version = "0.3.0+natcompsci.2025"
description = "A JAX-based library for simulating morphogenesis"
readme = "README.md"
license = {text = "Apache 2.0"}
authors = [
    {name = "Francesco Mottes", email = "fmottes@seas.harvard.edu"},
    {name = "Ramya Deshpande", email = "rdeshpande@seas.harvard.edu"}
]
urls = {Homepage = "https://github.com/fmottes/jax-morph"}
requires-python = ">=3.10"
dependencies = [
    "jax>=0.5.0",
    "jax-md @ git+https://github.com/jax-md/jax-md.git",
    "matplotlib>=3.10.0",
    "equinox>=0.12.2",
    "diffrax>=0.6.2",
    "optax>=0.2.4",
    "tqdm>=4.67.1",
    "networkx>=3.4.2",
]

[tool.setuptools.packages.find]
include = ["jax_morph*"]

[tool.black]
line-length = 250

[tool.ruff]
line-length = 250